# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image_transfer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14image_transfer.proto\"B\n\x0cImageRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x0f\n\x07\x63\x63tv_id\x18\x02 \x01(\t\x12\r\n\x05\x61lert\x18\x03 \x01(\x08\" \n\rImageResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2B\n\x14ImageTransferService\x12*\n\tPostImage\x12\r.ImageRequest\x1a\x0e.ImageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_transfer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_IMAGEREQUEST']._serialized_start=24
  _globals['_IMAGEREQUEST']._serialized_end=90
  _globals['_IMAGERESPONSE']._serialized_start=92
  _globals['_IMAGERESPONSE']._serialized_end=124
  _globals['_IMAGETRANSFERSERVICE']._serialized_start=126
  _globals['_IMAGETRANSFERSERVICE']._serialized_end=192
# @@protoc_insertion_point(module_scope)
