apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  namespace: cctv-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test-container
        image: leejeonghyeon1127/fastapi:1.0
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: code-volume
          mountPath: /app   # 파드 내부에서 볼륨을 마운트할 경로
      volumes:
      - name: code-volume
        hostPath:
          path: /home/CapstoneDesign/PythonRestAPI_V2   # 마스터 노드의 볼륨 경로
---
apiVersion: v1
kind: Service
metadata:
  name: test-service
  namespace: cctv-api
spec:
  type: NodePort
  selector:
    app: test
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
