apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cctvClusterRoleBinding
  namespace: cctv
subjects:
- kind: ServiceAccount
  name: cctv-api
  namespace: cctv
roleRef:
 kind: ClusterRole
 name: cctvManager
 apiGroup: rbac.authorization.k8s.io
